[package]
name = "mock-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "*", features = ["full"]}
axum = "*"
serde = { version = "*", features = ["derive"]}
serde_json = "*"
tower = "*"