[package]
name = "mock-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "*", features = ["full"]}
axum = "*"
serde = { version = "*", features = ["derive"]}
serde_json = "*"
tower = "*"

[dev-dependencies]
anyhow = "*"
httpc-test = "0.1.1"
