[package]
name = "mock-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "*", features = ["full"]}
serde = { version = "*", features = ["derive"]}
serde_json = "*"
warp = "*"
restaurant_benches = { path = "restaurant_benches" }





