[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]



[alias]
b32 = "build --release --target i686-pc-windows-msvc"
b = "build --release"
c = "check"
r = "run"
rr = "run --release"

