[target.x86_64-pc-windows-msvc]
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]
rustflags= [ "-C", "link-arg=-fuse-id=lid",]


[alias]
b32 = "build --release --target i686-pc-windows-msvc"
b = "build --release --target x86_64-pc-windows-msvc"
c = "check"
r = "run"
rr = "run --release"

[build]
target = ["x86_64-pc-windows-msvc"]
target-dir = "build"
