[alias]
b = "build --release --target x86_64-pc-windows-msvc && build --release --target i686-pc-windows-msvc"
c = "check"
r = "run"
rr = "run --release"


[build]
target = ["x86_64-pc-windows-msvc"]
target-dir = "build"
